version: 0.2

phases:
  pre_build:
    commands:
      - echo "Current working directory:"
      - pwd
      - chmod +x gradlew
      
  build:
    commands:
      - ./gradlew clean build

artifacts:
  files:
    - 'build/libs/*.jar'
  discard-paths: yes
